name: Rebuild Pull Request Comment

on:
  issue_comment:
    types:
      - created

jobs:
  rebuild:
    runs-on: ubuntu-20.04
    if: ${{ github.event.comment.body == 'rebuild'}}
    steps:
      - uses: actions/checkout@v2
      - name: Rebuild PR
        run: |
          title="${{github.event.pull_request}}"
          echo "PR is $title"

          pull_number=$(jq --raw-output .pull_request "$GITHUB_EVENT_PATH")
          echo "PR number is $pull_number"

          # Get jira id
          id=$(curl -X GET -u ${{secrets.JIRA_EMAIL}}:${{secrets.JIRA_COOKIE}} https://owletcare.atlassian.net/rest/api/3/issue/${{github.event.inputs.issueKey}}?fields=id | jq -r .id)
          echo $id

          # TODO: continue development on this once merged. Github Actions cannot be triggered until
          # they are on the base branch.
          # get PR id
          #pr=$(curl -X GET -u ${{secrets.JIRA_EMAIL}}:${{secrets.JIRA_COOKIE}} https://owletcare.atlassian.net/rest/dev-status/latest/issue/details?issueId=$id | jq -r '.detail[].pullRequests[0].id')
          #pr=$(echo $pr | sed 's/[^0-9]*//g')
          #echo $pr

          # update PR
          #curl -H "Accept: application/vnd.github.lydian-preview+json" -X PUT -u ${{secrets.USERNAME}}:${{secrets.USER_TOKEN}} https://api.github.com/repos/OwletCare/OwletCare-Android/pulls/$pr/update-branch
